---
services:
  lixee-dk6programmer:
    image: "lixee-dk6programmer"
    environment:
      FIRMWARE_URL: "https://github.com/fairecasoimeme/Zlinky_TIC/releases/download/v13.0/ZLinky_router_v13_limited.bin"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"

    ## Décommenter l'opération attendue
    # Afficher l'aide de DK6Programmer
    # command: [ "--help" ]
    
    # Lister les ports série
    command: [ "--list" ]

    # Flasher sans remise à zéro (Conserve les appareils déjà appairés)
    # command: [ "--verbosity", "2", "--nodevicereset", "--serial", "/dev/ttyUSB0", "--programbaud", "115200", "--force", "--program" ]

    # Flasher avec remise à zéro (Efface toutes les données, appairages compris)
    # command: [ "--verbosity", "2", "--nodevicereset", "--serial", "/dev/ttyUSB0", "--programbaud", "115200", "--erase", "FLASH", "--force", "--program" ]